### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by z0mbieslayer** [martindisch/Steamloader#1]
I keep getting errors while compiling. I know it's been awhile since you've done anything with this, but I can't get this to compile. I would like to integrate this with an application I am creating, and it would be extremely useful if I could just get a compiled version for windows.

**Comment by martindisch** [comment]
I'm not surprised it won't compile on Windows, as it expects to dynamically llink against libcurl for HTTP requests. Do you want to use this as a library in your code, or do you just need an executable that you can either run by hand or execute as a subprocess from your application?

**Comment by z0mbieslayer** [comment]
I just need an executable, I think that would be much easier for my current situation.

**Comment by martindisch** [comment]
Ok. I think trying to compile this on Windows is not the most productive thing to do. Writing this tool in C was pretty unnecessary in the first place, as it could've been done much more easily in about 10 lines of Python. I only did it as an exercise.

Now theoretically I could write a new version of this in Rust. That could be easily compiled for Windows and would also be much nicer on a technical level. But maybe I can help you directly query the API from your application, because it's actually very easy.
1. The endpoint is https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1. It takes some parameters from a POST request, encoded as `x-www-form-urlencoded` in the body:
* `itemcount` is the number of items you're requesting
* `publishedfileids[i]` is the ID of the ith item you want. So if you're looking up two, you're going to have `publishedfileids[0]=something` and `publishedfileids[1]=somethingelse`.
2. You'll receive a bunch of JSON, with details for each one of the files. What you want are the `file_url` values, because they're direct links to download the files. You can then download them with a simple GET request.

Here's a full working example of the first step, requesting the info of two workshop files. You need access to curl in your terminal, but even if you can't execute it, it should give you all the information you need.
```console
$ curl --location --request POST 'https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'itemcount=2' \
--data-urlencode 'publishedfileids[0]=2037141619' \
--data-urlencode 'publishedfileids[1]=2038618881'
```
The equivalent in Python:
```python
import requests

url = "https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1"
payload = 'itemcount=2&publishedfileids%5B0%5D=2037141619&publishedfileids%5B1%5D=2038618881'
headers = {
  'Content-Type': 'application/x-www-form-urlencoded'
}

response = requests.request("POST", url, headers=headers, data = payload)
print(response.text)
```

**Comment by z0mbieslayer** [comment]
Thank you so much, you've helped me a lot :)

**Comment by martindisch** [comment]
I'm glad that works for you. Let me know if there's anything else.

**Comment by z0mbieslayer** [comment]
One more question, sorry. How would I save the output to a text file? I'm not familiar with bash whatsoever, so it's probably a bit of a simple question.

**Comment by martindisch** [comment]
You can redirect the output of a command to a file instead of standard output (the terminal) by using `command > output.txt`. So for what I've given you that would be
```console
$ curl --location --request POST 'https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'itemcount=2' \
--data-urlencode 'publishedfileids[0]=2037141619' \
--data-urlencode 'publishedfileids[1]=2038618881' > fileinfo.json
```
But if you want to tell me more about your application and what programming language it's written in, I might be able to help you more.

**Comment by z0mbieslayer** [comment]
oops, I didn't see that you responded until now, sorry. I appreciate the help, and I did get it working so far. What would be an example of a working get request for file_url? I am writing a simple batch script, to answer your question. It's just a simple project I'm doing to help me learn more about batch. Thanks in advance.

**Comment by martindisch** [comment]
That depends on what you want to use to make that GET request (and presumably download the file). Using curl, it's as simple as `curl FILE_URL > file.extension`. So when downloading a mission file for Arma 3 for example, that would be `curl https://steamusercontent-a.akamaihd.net/ugc/1005932758869493519/C588CF64546B88AED7A9728C2D3C4B82AEFB2DF9/ > Road_To_Pyrgos.pbo`.

**Comment by z0mbieslayer** [comment]
Ah okay. How would I be able to grab the url from the json file, without knowing the exact url? I want to do this so I can set the url to a variable since I wouldn't know the exact url for every id.

**Comment by martindisch** [comment]
That's going to be tricky if you're only writing a Windows *.bat file, which I'm pretty sure is interpreted by good old CMD.exe. It requires parsing the JSON format somehow. There are definitely command line tools out there that allow you to specify what you're interested in, pipe in the source JSON and get that value as output. But as far as I'm aware there's nothing that can do that for you on a plain Windows installation, so you'd have to look for and install such a tool.

I think for your case you'd be much better off implementing what you want with a programming language such as Python, which makes it very easy to send requests to the API, extract useful information from the JSON and download and store the workshop file.

**Comment by z0mbieslayer** [comment]
So I'm trying to use a json parser called "jq" and I have a basic understanding on how to use it. However, I still can't get it to pipe the file_url part. It just keeps giving me errors. The reason I don't want to write this in python is because I'm writing it for a preexisting program already written in batch, so switching to python wouldn't be optimal. Sorry for spamming you by the way, I just really want to learn how to do this.

**Comment by z0mbieslayer** [comment]
Nevermind, just figured it out.

**Comment by z0mbieslayer** [comment]
Here's the solution that works for me:

`set /p addonid=What's your addon id?: `

`powershell -Command "Invoke-WebRequest https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe"`

`curl --location --request POST https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1 --header "Content-Type: application/x-www-form-urlencoded" --data-urlencode itemcount=1 --data-urlencode publishedfileids[0]=%addonid% -o fileinfo.json`

`FOR /F "delims=" %%i IN ('jq .response.publishedfiledetails[0].file_url fileinfo.json') DO set addonurl=%%i`

`del fileinfo.json`

`del jq.exe`

`curl -o temp.gma %addonurl%`

Like you said, I had to use a command line tool (jq) to parse the json and get the stuff I needed. But I'm surprised I was able to get it done with how little extra programs I needed.

**Comment by martindisch** [comment]
Very cool, I'm glad you were able to solve it! Always neat to see.

**Comment by z0mbieslayer** [comment]
Hey, just another small question: some addons that I'm downloading don't have a url in the file_url value, such as the addon id 2119764629. Do you know why this is? It's not a huge deal, I'm just curious as to why certain addons don't output a url.

**Comment by martindisch** [comment]
I don't know, maybe this is a special type of mod that can't be downloaded, or the actual files are somewhere else.

**Comment by z0mbieslayer** [comment]
Yeah, I'll have to do some more research and look more into it.

**Comment by z0mbieslayer** [comment]
So I think I found the problem. I found a thread about retrieving workshop items without steam on the gog forum, and a user said that IRemoteStorage interface is outdated and newer addons won't use it, which makes sense since the newer addons are the ones giving me trouble but the old ones work fine. These new addons use a new api called the ISteamUGC interface, so I will have to figure out how to use that one rather that the IRemoteStorage interface.

**Comment by martindisch** [comment]
Ah that makes a lot of sense. I remember reading something about this API being deprecated even when I first started using it. But I went with it anyway because it was easier to use than the other one where you needed an API key or something, at least at the time.
